name: CI/CD

on:
push:
  branches:
    - main

jobs:
build:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2
  - name: Configurar Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '14'
  - run: npm install
  - run: npm test
  - run: npm run build
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
